# config
configfile: "config/config.yaml"

# includes
include: "rules/fastqc.smk"
include: "rules/trim_galore.smk"
include: "rules/bowtie2.smk"

# rule all:
#     input:
#         expand("results/{FILE}.bam", FILE=config["FILES"])

rule all:
    input:
        config["RESULTPATH"] + "/done.txt"

rule done:
    input:
        expand(config["RESULTPATH"] + "/{FILE}.bam", FILE=config["FILES"])
    output:
        config["RESULTPATH"] + "/done.txt"
    shell:
        "echo Done > {output[0]}"